import {
  BOOKING_SLOT_MILLISECONDS,
  MAXIMUM_BOOKING_DURATION_MILLISECONDS,
} from '@mr-booking/booking-domain';

export const SCHEDULE_CLOCK_INTERVAL_MS = 60_000;
export const MAX_BOOKING_SLOT_COUNT =
  MAXIMUM_BOOKING_DURATION_MILLISECONDS / BOOKING_SLOT_MILLISECONDS;
export const COMPACT_ROW_HEIGHT_REM = 4.25;
export const STANDARD_ROW_HEIGHT_REM = 3.5;
